require:
  - rubocop-rake

inherit_gem:
  rubocop-inst:
  - rubocop.yml
  - rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 2.6

Naming/FileName:
  Exclude:
    - 'lib/faraday-oauth.rb'

Style/Documentation:
  Enabled: false
